version: '3.9'

services:

  cybint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cybint-core
    ports:
      - "8000:8000"
    networks:
      - cybint-net
    depends_on:
      - mongo
    restart: no

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - cybint-net
    restart: no

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - cybint-net
    depends_on:
      - mongo
    restart: no

networks:
  cybint-net:
    driver: bridge
